-- AlterTable
ALTER TABLE "Expense" ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "PaymentDetail" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
